Repository OpenSmock/OpenSmock, pull requests merged in 2025-06, with the labels that each got.

#75 CUDModel: fix model management when not known updated objects are cre…
  src/OpenSmock-Tests/SmockCUDModelTest.class.st
  src/OpenSmock/SmockCUDModel.class.st
Labels: bug

#76 Change protocol
  src/OpenSmock/SmockAbstractCoordinates.class.st
Labels: documentation

#77 Add method to remove all attributes
  src/OpenSmock-Tests/SmockAttributeListTest.class.st
  src/OpenSmock/SmockAttributeList.class.st
Labels: enhancement
